### ISSUE TITLE
webpackbar messes up stats.json

### ISSUE THREAD

**Issue by janein** [packmule/packmule#2]
When doing `webpack --mode production --profile --json > stats.json` I get some ugly lines at the beginning of my stats.json.
Seems to be this Problem: https://github.com/nuxt/webpackbar/issues/42
Is there any option I can set to fix this via packmule?

**Comment by thasmo** [comment]
Does `CI=true webpack --mode production --profile --json > stats.json` work?

**Comment by janein** [comment]
Nope, still printing those lines at the top of the file:
```
[09:22:25] [webpackbar] [INFO] Compiling Webpack
[09:22:41] [webpackbar] [SUCCESS] Webpack: Compiled successfully in 15.74s
{
  "errors": [],
  "warnings": [
 // ...
```

**Comment by thasmo** [comment]
@janein, this is an issue with nuxt/webpackbar#42 primarily. Nevertheless I may know a way to fix this with a workaround.

**Comment by thasmo** [comment]
Integrated a work around with a4e68596182e85d84f54a51d6ca4b3c8f6de11d9.
