### ISSUE TITLE
Assets are not loaded relative to partial in SASS

### ISSUE THREAD

**Issue by dfranek** [packmule/packmule#28]
If you have a structure like this:
```
scss/
|- main.scss
|- components/
|--- _footer.scss
images/
|- footer.png
```
If you now reference the footer.png file in the _footer.scss file with `background-image: url(../../images/footer.png);` the loader does not find the asset, because assets are always resolved relative to main.scss.

A solution would be to use this loader to correctly load assets:
https://github.com/bholloway/resolve-url-loader

**Comment by thasmo** [comment]
The next release will possibly feature the `resolve-url-loader` [in the sass-pack](https://github.com/packmule/packmule/blob/6c8fa8f6c2e2afbf1d1e12f1f0800ff4dfdc6626/packages/pack-sass/src/common/pack.ts#L63-L69), but unfortunately there's an [issue with `resolve-url-loader` in combination with the new dart-sass implementation](https://github.com/bholloway/resolve-url-loader/issues/122), which we use in the sass-pack.

**Comment by thasmo** [comment]
This was fixed somewhere upstream, see bholloway/resolve-url-loader#122 for context.
