### ISSUE TITLE
CDN support

### ISSUE THREAD

**Issue by thasmo** [packmule/packmule#47]
Support configuring CDN endpoints and integrate proper bundle creation to be served via CDN.

**Comment by thasmo** [comment]
Basic CDN support should be covered by using [`output.publicPath` in combination with an environment variable](https://webpack.js.org/guides/public-path/#use-cases).

**Comment by EmiiKhaos** [comment]
To which value would the asset path be set, when using a CDN? The webpack docs lack an example for that.

**Comment by thasmo** [comment]
Afaik the `publicPath` will just be appended to the generated bundle files; so `ASSET_PATH` in the example would be something like `https://cdn.com/path/to/bundle/` for production and `/path/to/bundle/` in development or similar.
