### ISSUE TITLE
Optimize CSS injection in development mode

### ISSUE THREAD

**Issue by thasmo** [packmule/packmule#7]
Currently CSS injection via the `style-loader` is not optimal because the initial injection (on page load) in development mode happens after the window's `load` event which causes scripts to behave differently in production mode.

One issue is that scripts which rely on the window's `load` event and need to read various DOM elements' properties (like dimensions, etc.) do not run correctly because the styles may be applied afterwards.

In production mode the CSS gets referenced via `link` tag and thus is always loaded before JS is executed, which is the intended behavior.

**Comment by jul1ans** [comment]
A workaround is to activate "singleton" in the style-loader options

**Comment by thasmo** [comment]
Maybe also related to https://github.com/nolimits4web/swiper/issues/2218 - we mainly encounter the issue in combination with Swiper.

**Comment by thasmo** [comment]
Please feel free to reopen if the problem still exists or occurs again with the latest version `1.3.0`.
