### ISSUE TITLE
XSS vulnerability from serialize-javascript

### ISSUE THREAD

**Issue by janein** [packmule/packmule#81]
There is a xss vulnerability from a dependency to serialize-javascript.

![image](https://user-images.githubusercontent.com/1932912/72601394-9e3b3c00-3915-11ea-8da1-035f59e1c02c.png)

The dependency is fixed in the latest version of compression-webpack-plugin. So if we could update this dependency, the issue should be resolved.

packmule-version: 1.0.0

**Comment by thasmo** [comment]
As stated in https://www.npmjs.com/advisories/1426, `This vulnerability does not affect Node.js applications.`, so this should not be an issue in this case. Nevertheless, I have updated the compression plugin and released `1.0.1` for that matter.
