### ISSUE TITLE
Messed up stats.json

### ISSUE THREAD

**Issue by janein** [packmule/packmule#93]
Similar to isse #2 the stats.json gets messed up when calling `webpack --env.production --profile --json > stats.json`.

At the top of the file you can see something like this:
```
ℹ Compiling Webpack
✔ Webpack: Compiled successfully in 8.78s
```

Any idea where they come from?

Not a huge bug, but it's still annoying as you always have to manually delete those lines.

**Comment by thasmo** [comment]
Fixed by 291272c98f95bbae969016a3e6b7333b0cb04c66.
